import { ClerkProvider } from "@clerk/nextjs"
import { frFR } from "@clerk/localizations"
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}
import { Logo } from "@/components/Logo"
import "../(main)/globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider localization={frFR}>
      <html lang='fr'>
        <body className='h-screen flex flex-col justify-center items-center gap-4 text-3xl'>
          <Logo />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
